blank_issues_enabled: false
contact_links:
  - name: AppLovin Mediation Bidon Adapter Documentation
    url: https://docs.bidon.org/docs/applovin-max/sdk-integration
    about: The place to get started with Bidon Adapter.
